version: 2
jobs:
  build:
    working_directory: ~/picket
    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm install
      - run: git submodule init
      - run: git submodule update
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run integration-test
      - run: npm run build



